# Using the official NGINX image as base
FROM nginx:alpine

# Setting the working directory
WORKDIR /usr/share/nginx/html

# Copying files into the container
COPY . .
COPY login-page.html index.html

# Expose port 80
EXPOSE 80

#Start Nginx when container starts
CMD ["nginx", "-g", "daemon off;"]
